#!/bin/sh

images=$(find ./backgrounds -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif")

true > ./backgrounds/index.txt

for path in $images; do
  image=$(basename "$path")
  author=$(basename "$(dirname "$path")")
  echo "$author/$image = $path"
  echo "$author/$image" >> ./backgrounds/partial.txt
done

sort -R ./backgrounds/partial.txt > ./backgrounds/index.txt
rm -f ./backgrounds/partial.txt
