#!/bin/sh

extensions="png jpeg gif"

for ext in $extensions; do
  find ./backgrounds -name "*.$ext" -exec mogrify -format jpg {} +
done

# Optimize jpg images
echo "Optimizing jpg images"
find ./backgrounds -name "*.jpg" -exec jpegoptim -m 80 {} \;
