#!/bin/sh

extensions="png jpeg gif"

for ext in $extensions; do
  images=$(find ./backgrounds -name "*.$ext")

  if [ -n "$images" ]; then
    echo "Converting $ext images to jpg"
    mogrify -format jpg "$images"

    for f in $images; do
      rm -f "$f"
    done
  fi
done

# Optimize jpg images
echo "Optimizing jpg images"
find ./backgrounds -name "*.jpg" -exec jpegoptim -m 80 {} \;